version: '3.8'

services:

  mongo-db:
    image: mongo
    ports:
      - '27017:27017'

  mongo_seed:
    build: mongoseed
    image: mongo_seed
    links:
      - mongo-db
  
  server:
    build: backend
    image: magyarr91/simpletest_backend
    ports:
      - '3000:3000'
    links:
      - mongo-db
  client:
    build: frontend/simpletest-frontend
    image: magyarr91/simpletest_frontend
    ports:
      - '80:80'